# Generated by Django 4.0.4 on 2022-09-16 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='reaction_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.reactiontype'),
        ),
    ]
