# Generated by Django 4.0.4 on 2022-09-19 14:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_reaction_type_id_student_reaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 9, 19, 14, 57, 53, 380864, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
