# Generated by Django 4.0.4 on 2022-09-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_question_unvoted_by_question_voted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='unvoted_by',
            field=models.ManyToManyField(blank=True, related_name='unvoted_question_set', to='core.student'),
        ),
        migrations.AlterField(
            model_name='question',
            name='voted_by',
            field=models.ManyToManyField(blank=True, related_name='voted_question_set', to='core.student'),
        ),
    ]
