# Generated by Django 4.0.4 on 2022-09-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_student_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
    ]
