# Generated by Django 3.0.4 on 2022-09-14 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_session_sessiontoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='instructor_id',
            new_name='instructor',
        ),
        migrations.RenameField(
            model_name='sessiontoken',
            old_name='session_id',
            new_name='session',
        ),
    ]
