# Generated by Django 4.0.4 on 2022-09-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reactiontype_student_reaction_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
