# Generated by Django 4.0.4 on 2022-09-18 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_question_vote_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='session_id',
            new_name='session',
        ),
    ]
