# Generated by Django 4.0.4 on 2022-09-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_student_id_question_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='reaction_type_id',
            new_name='reaction_type',
        ),
    ]
