# Generated by Django 4.0.4 on 2022-09-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_reaction_type_id_student_reaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='unvoted_by',
            field=models.ManyToManyField(blank=True, related_name='unvoted_by_set', to='core.student'),
        ),
        migrations.AddField(
            model_name='question',
            name='voted_by',
            field=models.ManyToManyField(blank=True, related_name='voted_by_set', to='core.student'),
        ),
    ]
