# Generated by Django 4.0.4 on 2022-09-20 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_session_created_date_time'),
        ('core', '0010_alter_question_unvoted_by_alter_question_voted_by'),
    ]

    operations = [
    ]
